# Generated by Django 6.0.1 on 2026-01-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_savings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
