# Generated by Django 6.0.1 on 2026-01-29 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_savings', '0002_delete_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysaving',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysaving',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
    ]
