# Generated by Django 6.0.1 on 2026-01-31 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_savings', '0003_monthlysaving_created_at_monthlysaving_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('affected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_savings', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
